name: yosys-verific CI

on:
  workflow_dispatch:
  push:

jobs:
  msvc:
    name: msvc
    runs-on: windows-latest
    defaults:
        run:
            shell: pwsh
    steps:
    
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v2
    - uses: cygwin/cygwin-install-action@master
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    - name: Build yosys_verific_rs
      run: |
        cmake --build . --config Release
